language: node_js
node_js:
    - "6.10"

services:
  - mongodb

before_script:
    - cd server/
    - npm install

script:
    - npm run coverage
    - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
