version: '3'
services:
    iClientMongoServer:
        image: mongo:3.4
        container_name: iClientMongoServer
        restart: always
        volumes:
         - iClientMongoData:/data/db

    iClientNodeServer:
        image: node:6.10
        container_name: iClientNodeServer
        restart: always
        environment:
         - DATABASE_ICLIENT=${DATABASE_ICLIENT}
         - SECRET_ICLIENT=${SECRET_ICLIENT}
        command: bash -c 'cd /server/ && npm install && node /server/index.js'
        ports:
         - "3000:3000"
        volumes:
         - ./server:/server
        tty: true

volumes:
    iClientMongoData:
        driver: "local"
